### PR TITLE
2015 04 07 jsonfixes

### PR DESCRIPTION
**Pull request by jlicht**

### CODE REVIEW

**Comment by jlicht** [comment]
@michael-lts I made a bunch of comments - can you take a look? Thanks, Jeff

**Comment by michael-lts** [comment]
Yep, will do, thanks!
Michael

**Comment by jlicht** [comment]
@michael-lts: Possible bug, that doesn't exist on production:

QA: ```curl http://ec2-54-175-71-73.compute-1.amazonaws.com/v2/items?blah=blah``` returns a 500 error code and null pointer exception
Live:  ```curl http://api.lib.harvard.edu/v2/items?blah=blah``` returns a 400 code and error message

**Comment by jlicht** [comment]
@michael-lts  Merged into develop

**Pull request merged**
